### ISSUE TITLE
Can't resolve any steps

### ISSUE THREAD

**Issue by geerzo** [kumaraman21/IntelliJBehave#23]
I am using IntelliJ 12 so that might be causing the problem but every step I have is highlighted as "No Definition Found for Step" even though the stories run just fine. 

Syntax highlighting works just fine though.

**Comment by kevoriordan** [comment]
Same issue here.

**Comment by bogdartysh** [comment]
as for me 
1.  project build ok
2. mvn install executes stories correctly
3.  I've tried to remove all .ideas files and reopen the IDE without any effect.
4. also tried to analyze-> inspect code the plugin fails with an error  

> 17:16:29 Throwable
>          Tokens [STEP_TYPE, STEP_TEXT, WHITE_SPACE, STORY_DESCRIPTION, WHITE_SPACE, STORY_DESCRIPTION, STEP_TYPE, STEP_TEXT, WHITE_SPACE, STORY_DESCRIPTION, WHITE_SPACE, STORY_DESCRIPTION, WHITE_SPACE, STORY_DESCRIPTION, WHITE_SPACE, STORY_DESCRIPTION, WHITE_SPACE, STORY_DESCRIPTION, WHITE_SPACE, STORY_DESCRIPTION, WHITE_SPACE, STORY_DESCRIPTION, WHITE_SPACE, STORY_DESCRIPTION, WHITE_SPACE, STORY_DESCRIPTION, WHITE_SPACE, STORY_DESCRIPTION, WHITE_SPACE] were not inserted into the tree. Language: Story, Text:
>          Meta:
>          @categories bom"
